spring:
    application:
        name: inventory
    datasource:
        url: jdbc:h2:mem:inventory;DATABASE_TO_UPPER=false
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
    jackson:
        default-property-inclusion: non_null
server:
    error:
        include-message: always
        include-binding-errors: always