spring:
    application:
        name: inventory
    datasource:
        url: jdbc:h2:mem:inventory
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true